In [2]:
from sklearn.datasets import load_diabetes
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [3]:
X,y=load_diabetes(return_X_y=True)

In [4]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

# Implementation by Linear Regression Class

In [5]:
reg=LinearRegression()
model=reg.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [6]:
r2_score(y_test,y_pred)*100

43.99387660024645

In [7]:
model.coef_ #checking values of betas

array([  -9.16088483, -205.46225988,  516.68462383,  340.62734108,
       -895.54360867,  561.21453306,  153.88478595,  126.73431596,
        861.12139955,   52.41982836])

In [8]:
model.intercept_ #checking value of beta note

151.88334520854633

In [9]:
X_train.shape

(353, 10)

# Implementing Batch Gradient Descent

In [14]:
import random

class MBGDRegressor:

    def __init__(self,batch_size,learning_rate=0.01,epochs=100):

        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size

    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):

            for j in range(int(X_train.shape[0]/self.batch_size)):

                idx = random.sample(range(X_train.shape[0]),self.batch_size)

                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)

        print(self.intercept_,self.coef_)

    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [31]:
gd=MBGDRegressor(batch_size=int(X_train.shape[0]/10),learning_rate=0.01,epochs=150)

In [32]:
model1=gd.fit(X_train,y_train)

152.2671050635076 [  11.68005839 -175.82184045  503.36062844  321.7299657   -45.67731874
 -129.37565563 -190.46154204   95.16027162  463.90846251   97.78922806]


In [33]:
y_pred=gd.predict(X_test)

In [34]:
r2_score(y_test,y_pred)

0.4519188400727837

# using sklearn

In [35]:
from sklearn.linear_model import SGDRegressor


In [36]:
sgd=SGDRegressor(learning_rate='constant',eta0=0.1)

In [60]:
batch_size=29

for i in range(100):
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [61]:
sgd.coef_

array([ -13.42201244, -202.35586303,  500.90513998,  330.74158195,
        -41.49087392, -118.72799994, -205.76829256,   97.31550029,
        497.67886613,   78.86511238])

In [62]:
sgd.intercept_

array([150.0433485])

In [63]:
y_pred=sgd.predict(X_test)

In [64]:
r2_score(y_test,y_pred)

0.4511394342883783